version: "3.9"


services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: newsela
      POSTGRES_PASSWORD: newsela-password
      POSTGRES_DB: newsela_db
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
